SELECT * FROM T_USER;
SELECT * FROM PRODUCT;
SELECT * FROM P_MANAGE;
SELECT * FROM REVIEW;
SELECT * FROM ORDER_TABLE;
SELECT * FROM T_CODE;

SELECT P.* , C.NAME
FROM PRODUCT P
LEFT JOIN T_CODE C ON P.KIND = C.CODE AND C.KIND = 'CLOTH'
;

SELECT O.P_ID , O.ID, U.NAME, C.NAME
FROM ORDER_TABLE O
INNER JOIN T_USER U ON U.ID = O.ID
LEFT JOIN T_CODE C ON O.STATUS = C.CODE AND C.KIND = 'STATUS'
WHERE O.STATUS = 'E'
;

-- 1. 주문내역에서 유재석이 주문한 제품의 주문한 사람의 이름, 제품의 이름, 판매가격,
-- 제품종류(상의, 하의인지 등), 배송상태(배송전, 배송후 등) 출력
SELECT DISTINCT U.NAME ,  P.P_NAME , P.S_PRICE , C.NAME AS 배송상태 , C2.NAME AS 제품종류
FROM T_USER U
INNER JOIN ORDER_TABLE O ON U.ID = O.ID
INNER JOIN PRODUCT P ON P.P_ID = O.P_ID
LEFT JOIN T_CODE C ON O.STATUS = C.CODE AND C.KIND = 'STATUS'
LEFT JOIN T_CODE C2 ON P.KIND = C2.CODE AND C2.KIND = 'CLOTH'
WHERE U.NAME = '유재석'
;

SELECT U.NAME , P.P_NAME , P.S_PRICE , C.NAME AS 제품종류 , C2.NAME AS 제품상태
FROM ORDER_TABLE O
INNER JOIN T_USER U ON O.ID = U.ID
INNER JOIN PRODUCT P ON O.P_ID = P.P_ID
LEFT JOIN T_CODE C ON C.KIND = 'CLOTH' AND C.CODE = P.KIND
LEFT JOIN T_CODE C2 ON C2.KIND = 'STATUS' AND O.STATUS = C2.CODE
WHERE U.NAME = '유재석'
;


SELECT DISTINCT U.NAME , P.P_NAME , C4.NAME AS 색깔 , C.NAME AS 제품종류 , C2.NAME AS 결제방법 , C3.NAME AS 배송상태
FROM ORDER_TABLE O
INNER JOIN T_USER U ON O.ID = U.ID
INNER JOIN PRODUCT P ON P.P_ID = O.P_ID
LEFT JOIN T_CODE C ON C.KIND = 'CLOTH' AND C.CODE = P.KIND
LEFT JOIN T_CODE C2 ON C2.KIND = 'PURCHASE' AND C2.CODE = O.PURCHASE
LEFT JOIN T_CODE C3 ON C3.KIND = 'STATUS' AND O.PURCHASE = C3.CODE
LEFT JOIN T_CODE C4 ON C4.KIND = 'COLOR' AND O.COLOR = C4.CODE
WHERE C.NAME = '모자'

;

-- 1. 가장 재고가 많이 남은 제품의 제품명, 제품종류, 남은 갯수 출력

-- 2. 유재석이 구매한 '모자' 제품의 각 사이즈별 수량 구하기
SELECT SUM(CNT_ALL)
FROM(

SELECT M.COUNT AS CNT_ALL
FROM ORDER_TABLE O
INNER JOIN T_USER U ON O.ID = U.ID
INNER JOIN PRODUCT P ON O.P_ID = P.P_ID
INNER JOIN P_MANAGE M ON O.P_ID = M.P_ID
INNER JOIN T_CODE C ON P.KIND = C.CODE AND C.NAME = '모자'

WHERE U.NAME = '유재석'
)



-- 3. 한번도 주문이 되지 않은 제품의 S 사이즈 제품들 삭제
-- 4. 배송상태가 '환불' 인 제품들의 재고량 구하기





